# Generated by Django 2.2 on 2021-07-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0004_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message_content',
        ),
    ]
