# Generated by Django 2.2 on 2021-07-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0005_auto_20210715_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_content',
            new_name='content',
        ),
    ]
