# Generated by Django 2.2 on 2021-07-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0006_auto_20210715_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='comments_user_liked', to='the_wall_app.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='messages_user_liked', to='the_wall_app.User'),
        ),
    ]
