# Generated by Django 2.2 on 2021-07-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tvshows_app', '0004_auto_20210712_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
