# Generated by Django 2.2 on 2021-07-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tvshows_app', '0005_auto_20210712_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
