# Generated by Django 2.2 on 2021-07-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.CharField(max_length=255, null='TRUE'),
            preserve_default='TRUE',
        ),
    ]
