# Generated by Django 2.2 on 2021-07-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0002_user_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm',
            new_name='confirm_password',
        ),
    ]
