# Generated by Django 2.2 on 2021-07-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_by_id',
            new_name='uploaded_by',
        ),
    ]
