# Generated by Django 2.2 on 2021-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0003_auto_20210717_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users_who_favorited',
            field=models.ManyToManyField(related_name='books_user_favorited', to='fav_books_app.User'),
        ),
    ]
